name = "ArchiverService"
uuid = "8054f2ab-3db8-4d11-8f14-d3e261bc0a4e"
version = "0.1.0"

[deps]
Aeron = "42ac8a32-990f-4d8c-aece-52d731103226"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
AstroImages = "fe3fc30c-9b16-11e9-1c73-17dabf39f4ad"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Hsm = "8e6e8f70-f28c-415d-b881-3282d03f8261"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RTCBlock = "7cdd706b-019a-4a3b-a434-76f5582fd181"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SimpleBinaryEncoding = "165d4630-7e21-4626-b3c2-016fbf5108c4"
SpidersMessageEncoding = "25d647a0-ef7d-4da3-8ba8-11abaa3d526c"
SpidersMessageSender = "1be38944-6f3b-4e31-8ac7-3d1d5d2dec34"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"

[compat]
Aeron = "2.0.0"
ArgParse = "1.2.0"
Hsm = "0.2.1"
MD5 = "0.2.3"
Mmap = "1.11.0"
Printf = "1.11.0"
RTCBlock = "0.1.0"
SimpleBinaryEncoding = "3.0.0"
SpidersMessageEncoding = "3.1.2"
SpidersMessageSender = "0.1.0"
